sudo: required
services: 
  - docker

before_install:
  - docker build -t madhusampangi/say -f Dockerfile .
script:
  - docker ps

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Say"
  env: "SayText"
  bucket_name: "elasticbeanstalk-ap-south-1-133432355865"
  bucket_path: "Say"
  on:
      branch: master
  access_key_id: $API_KEY
  secret_access_key:
      secure: "$API_SECRET"